/**
 * Copyright © 2018 spring-data-dynamodb-example (https://github.com/derjust/spring-data-dynamodb-examples)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.samples.petclinic.customers.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverter;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.UUID;
import java.util.Date;
import java.util.List;


@DynamoDBTable(tableName = "OWNER")
public class Owner{
    
    @DynamoDBHashKey
	@DynamoDBAutoGeneratedKey()
	private UUID id;
	private String firstName;
	private String lastName;
	private String address;
	private String city;
	private String telephone;
	private List<Pet> pets;
	
	public Owner(String firstName, String lastName, String address, String city, String telephone, List<Pet> pets){
	    this.firstName = firstName;
	    this.lastName = lastName;
	    this.address = address;
	    this.city = city;
	    this.telephone = telephone;
	    this.pets = pets;
	}
	
	public Owner(){
	    
	}
	
	public UUID getId() {
        return id;
    }
    
    public void setId(UUID id){
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(final String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(final String lastName) {
        this.lastName = lastName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
	
	public List<Pet> getPets(){
	    return pets;
	}
	
	public void setPets(List<Pet> pets){
	    this.pets = pets;
	}
}