/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT-0
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package org.springframework.samples.petclinic.visits.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverter;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.UUID;
import java.util.Date;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonFormat;

@DynamoDBTable(tableName = "VISIT")
public class Visit {

   
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	private UUID id;
	
    private Date date;
    
    private String petName;
    private String ownerId;
    private String description;
    
    public Visit(){
        
    }
    
    public UUID getId(){
        return id;
    }
    
    public void setId(UUID id){
        this.id = id;
    }
    
    public Visit(String ownerId, String petName, Date date){
        this.petName = petName;
        this.ownerId = ownerId;
        this.date = date;
    }
    
    public Date getDate() {
        return date;
    }
    
    public void setDate(Date date){
        this.date = date;
    }

    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description){
        this.description = description;
    }

    public String getPetName() {
        return petName;
    }

    public void setPetName(final String petName) {
        this.petName = petName;
    }
    
    public String getOwnerId(){
        return ownerId;
    }
    
    public void setOwnerId(String ownerId){
        this.ownerId = ownerId;
    }

}
